version: "3"

services:
  itho-api-ts:
    image: philipsen/itho-api-ts:v0.0.1
    build: ./itho-api-ts
    volumes:
      - ./itho-api-ts:/app
    ports:
      - "3001:3000"
    networks:
      - front      
  itho-app:
    image: philipsen/itho-app
    build: ./itho-app
    ports:
      - "80:80"
    networks:
      - front
networks: 
  front:
