version: "3"

services:
  pubsub:
    image: philipsen/app-mqtt
    build: app-mqtt
    networks: 
      - "front"
    ports: 
      - "1883:1883"
  api:
    image: philipsen/api
    build: ./api
    command: nodemon server.js
    volumes:
      - ./api:/app
      - /app/node_modules
    ports:
      - "8080:8080"
    networks:
      - front
  itho-app2:
    #container_name: itho-app2
    build: 
      context: itho-app
      dockerfile: Dockerfile-local
    ports:
      - "80:80"
      - "49153:49153"
    volumes:
      - ./itho-app:/app  
    networks:
      - front 
  mongo:
    image: mongo
    volumes:
      - ./data:/data/db
    #ports:
    #  - "27017:27017"
    networks: 
      - front
networks: 
  front:
