version: "3"

services:
  pubsub:
    image: philipsen/app-mqtt
    build: app-mqtt
    networks: 
      - "front"
    ports: 
      - "1883:1883"
  itho-api:
    image: philipsen/itho-api
    build: ./api
    command: nodemon server.js
    volumes:
      - ./api:/app
      - /app/node_modules
    ports:
      - "8080:8080"
    networks:
      - front
  itho-app:
    build: 
      context: itho-app
      dockerfile: Dockerfile-dev
    ports:
      - "4200:4200"
      - "49153:49153"
    volumes:
      - ./itho-app:/app  
    networks:
      - front
  itho-proxy:
    build:
      context: itho-proxy
      dockerfile: Dockerfile-dev
    ports:
      - "80:80"
    networks:
      - front
  mongo:
    image: mongo
    volumes:
      - ./data:/data/db
    networks: 
      - front
networks: 
  front:
