version: "3"

services:
  itho-api:
    image: philipsen/itho-api
    build: ./itho-api
    command: nodemon server.js
    volumes:
      - ./itho-api:/app
      - /app/node_modules
    ports:
      - "8080:8080"
    networks:
      - front

  itho-api-ts:
    image: philipsen/itho-api-ts
    build: ./itho-api-ts
    volumes:
      - ./itho-api-ts:/app
    ports:
      - "3001:3000"
    networks:
      - front      
  itho-app:
    image: philipsen/itho-app
    build: ./itho-app
    ports:
      - "80:80"
    networks:
      - front
networks: 
  front:
