version: "3"

services:
  pubsub:
    image: eclipse-mosquitto
    networks: 
      - "front"
    ports: 
      - "1883:1883"
  api:
    #image: api:v2
    build: ./api
    command: nodemon server.js
    volumes:
      - ./api:/app
    ports:
      - "8080:8080"
      - "5858:5858"
    networks:
      - front
networks: 
  front: