version: "3"

services:
  pubsub:
    image: eclipse-mosquitto
    networks: 
      - "front"
    ports: 
      - "1883:1883"
  itho-api:
    image: philipsen/itho-api
    build: ./itho-api
    command: nodemon server.js
    volumes:
      - ./itho-api:/app
      - /app/node_modules
    ports:
      - "8080:8080"
      #- "5858:5858"
    networks:
      - front
  itho-app:
    image: philipsen/itho-app
    build: ./itho-app
    ports:
      - "80:80"
    networks:
      - front
  mongo:
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
    networks: 
      - front
networks: 
  front:
