version: "3"

services:

  itho-api-ts:
    build: 
      context: itho-api-ts
      dockerfile: Dockerfile-dev
    ports:
      - "8081:8081"
    environment:
      - "MONGODB_URI_LOCAL=mongodb+srv://itho:aapnootmies@cluster0-xqsdh.mongodb.net/test2?retryWrites=false"
      - "MQTT_HOST=167.99.32.103"
      - MQTT_USER=itho
      - MQTT_PASSWD=aapnootmies
    volumes:
      - ./itho-api-ts:/app
    networks:
      - front
  itho-app:
    build: 
      context: itho-app
      dockerfile: Dockerfile-dev
    ports:
      - "4200:4200"
      - "49153:49153"
    volumes:
      - ./itho-app:/app  
    networks:
      - front
  itho-proxy:
    build:
      context: itho-proxy
      dockerfile: Dockerfile-dev
    ports:
      - "81:81"
    networks:
      - front
    depends_on: 
      - itho-app
      - itho-api-ts
networks: 
  front:
