kind: Service
apiVersion: v1
metadata:
  name:  itho-app
spec:
  selector:
    app:  itho-app
  type:  LoadBalancer
  ports:
  - name:  ext
    port:  80
    targetPort:  80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: itho-app
spec:
  selector:
    matchLabels:
      app: itho-app
  template:
    metadata:
      labels:
        app: itho-app
    spec:
      containers:
      - name: itho-app
        image: philipsen/itho-app
        ports:
        - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: itho-api
spec:
  selector:
    app: itho-api
  ports:
  - port: 8080
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: itho-api
spec:
  selector:
    matchLabels:
      app: itho-api
  template:
    metadata:
      labels:
        app: itho-api
    spec:
      containers:
      - name: itho-api
        image: philipsen/itho-api-ts:v0.0.1
        imagePullPolicy: Always
        env:
        - name:  MQTT_HOST
          value: 167.99.32.103 
        - name: MQTT_USER
          value: itho
        - name: MQTT_PASSWD
          value:  aapnootmies 
        - name: MONGODB_URI_LOCAL
          value: mongodb+srv://itho:aapnootmies@cluster0-xqsdh.mongodb.net/test?retryWrites=false  
        ports:
        - containerPort: 8080

