apiVersion: apps/v1
kind: Deployment
metadata:
  name: itho-api
spec:
  selector:
    matchLabels:
      app: itho-api
  template:
    metadata:
      labels:
        app: itho-api
    spec:
      containers:
      - name: itho-api
        image: philipsen/itho-api-ts:{{ .Values.imageTag }}
        imagePullPolicy: Always
        env:
        - name:  MQTT_HOST
          value: {{ .Values.mqttHost }}
        - name: MQTT_USER
          value: {{ .Values.mqttUser }}
        - name: MQTT_PASSWD
          value: {{ .Values.mqttPasswd }} 
        - name: MONGODB_URI_LOCAL
          value: {{ .Values.mongoUri }}  
        ports:
        - containerPort: 8080
